name: Build Android debug APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK components
        uses: r0adkll/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'
          components: platform-tools,platforms;android-33

      - name: Make gradlew executable
        run: |
          chmod +x android_receiver/gradlew || true

      - name: Build debug APK
        working-directory: android_receiver
        run: |
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android_receiver/app/build/outputs/apk/debug/app-debug.apk

      - name: Commit APK back to repository
        run: |
          cp android_receiver/app/build/outputs/apk/debug/app-debug.apk $GITHUB_WORKSPACE/app-debug.apk
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add app-debug.apk || true
          git commit -m "Add built app-debug.apk [ci]" || echo "no changes to commit"
          git push origin HEAD:main || echo "push failed"

